# Practice on NumPy and pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create NumPy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on NumPy arrays


## Part 1: Creating NumPy arrays.

1. Please create a NumPy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Please create a numpy array containing the values from 1 to 10.
-  Please create a numpy array from 0 to 5 with a step size of 0.2
- Create a numpy array with the shape 2,3 with random values


In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression  
my_list = [1, 2, 5, 6, 8]
np_array = np.array(my_list)
print('Numpy Array:', np_array)

Numpy Array: [1 2 5 6 8]


2. Please create a NumPy array containing the values from 1 to 10.


In [10]:
numpy_array = np.arange(1, 11)
print('Numpy Array using arange:', numpy_array)

Numpy Array using arange: [ 1  2  3  4  5  6  7  8  9 10]


In [11]:
python_list = range(1, 11)
print('Python List:', list(python_list))

Python List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


3. Please create a NumPy array from 0 to 5 with a step size of 0.2


In [12]:
numpy_array = np.arange(0, 5.2, 0.2)
print('Numpy Array using arange:', numpy_array)

Numpy Array using arange: [0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5. ]


4. Create a NumPy array with the shape 2,3 with random values


In [13]:
np.random.rand(2, 3)

array([[0.17616692, 0.53080753, 0.29687182],
       [0.82410676, 0.70574702, 0.13212679]])

## Part 2: Manipulate NumPy arrays.

1. Please create a NumPy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.


In [24]:
my_lst_array = np.array([1, 3, '4', 5, 12, '0'], np.int32) 

print(my_lst_array)

[ 1  3  4  5 12  0]


2. Check the data type of the objects and the shape of the array


In [25]:
print(my_lst_array.dtype)

int32


3. Update the 4th value to 30.


In [69]:
my_lst_array = np.array([1, 3, '4', 5, 12, '0'], dtype=object) # Here, we are specifying that the array elements can be of any type with object data type
my_lst_array[3] = 30 # Now this works without an error as all elements are strings initially and then after assignment, it changes from string to integer. [2]
print(my_lst_array)

[1 3 '4' 30 12 '0']


4. Reshape the array to a 2x3 matrix.


In [70]:
import numpy as np
reshape_2d = my_lst_array.reshape(2, 3)
print(reshape_2d)

[[1 3 '4']
 [30 12 '0']]


5. Please add 8 to each value in the first row and 12 to each in the second row.


In [72]:
reshape_2d = reshape_2d.astype(np.int32)

print("dtype nach Konvertierung:", reshape_2d.dtype)
print(reshape_2d)

# Add 8 to first row, 12 to second row
reshape_2d[0] += 8
reshape_2d[1] += 12
print("After adding:", reshape_2d)


dtype nach Konvertierung: int32
[[ 9 11 12]
 [42 24 12]]
After adding: [[17 19 20]
 [54 36 24]]


6. Multiply the first column with 2, the second with 3 and the third with 4.


In [73]:
reshape_2d[:,0] *= 2
reshape_2d[:,1] *= 3
#reshape_2d[:,2] = *= 4
print("After multiplying columns:", reshape_2d)


After multiplying columns: [[ 34  57  20]
 [108 108  24]]


7. Please sum up all numbers in the first row, and all numbers in the second row.


In [74]:
reshape_2d.sum(axis=1)  # Sum of each row

array([111, 240])

8. Similarly, search for the largest number for each column.


In [75]:
reshape_2d.max(axis=0)  # Max of each column

array([108, 108,  24], dtype=int32)

9. Extract the number in the second column and the first row.


In [76]:
value = reshape_2d[0,1]
print("Value at first row, second column:", value)

Value at first row, second column: 57


10. Check at which index the value is exactly 48.

In [78]:
print(np.where(reshape_2d == 57))

(array([0]), array([1]))
